// items.js — ПОЛНОСТЬЮ ОБНОВЛЁННАЯ ВЕРСИЯ (на декабрь 2025)
// Используется как на клиенте, так и на сервере (если нужно)

const e = require("express");

const ITEM_CONFIG = {
  // === ЕДА / НАПИТКИ ===
  energy_drink: {
    effect: { energy: 20, water: 5 },
    description: "Энергетик: +20 эн. +5 воды.",
    rarity: 2,
    canBeAutoSpawned: true,
    canDropFromEnemy: true,
  },
  nut: {
    effect: { food: 7 },
    description: "Орех: +7 еды.",
    rarity: 3,
    canBeAutoSpawned: true,
    canDropFromEnemy: true,
  },
  water_bottle: {
    effect: { water: 30 },
    description: "Вода: +30 воды.",
    rarity: 3,
    canBeAutoSpawned: true,
    canDropFromEnemy: true,
  },
  apple: {
    effect: { food: 8, water: 5 },
    description: "Яблоко: +8 еды, +5 воды.",
    rarity: 3,
    canBeAutoSpawned: true,
    canDropFromEnemy: true,
  },
  berries: {
    effect: { food: 6, water: 6 },
    description: "Ягоды: +6 еды, +6 воды.",
    rarity: 3,
    canBeAutoSpawned: true,
    canDropFromEnemy: true,
  },
  carrot: {
    effect: { food: 5, energy: 3 },
    description: "Морковь: +5 еды, +3 энергии.",
    rarity: 3,
    canBeAutoSpawned: true,
    canDropFromEnemy: true,
  },
  canned_meat: {
    effect: { food: 20 },
    description: "Банка тушёнки: +20 еды.",
    rarity: 1,
    canBeAutoSpawned: true,
    canDropFromEnemy: true,
  },
  mushroom: {
    effect: { food: 5, energy: 15 },
    description: "Гриб прущий: +15 энергии, +5 еды.",
    rarity: 1,
    canBeAutoSpawned: true,
    canDropFromEnemy: true,
  },
  sausage: {
    effect: { food: 16, energy: 3 },
    description: "Колбаса: +16 еды, +3 энергии.",
    rarity: 2,
    canBeAutoSpawned: true,
    canDropFromEnemy: true,
  },
  blood_pack: {
    effect: { health: 40 },
    description: "Пакет крови: +40 здоровья.",
    rarity: 1,
    canBeAutoSpawned: true,
    canDropFromEnemy: true,
  },
  bread: {
    effect: { food: 13, water: -2 },
    description: "Хлеб: +13 еды, -2 воды.",
    rarity: 2,
    canBeAutoSpawned: true,
    canDropFromEnemy: true,
  },
  vodka_bottle: {
    effect: { health: 5, energy: -2, water: 1, food: 2 },
    description: "Водка: +5 здоровья, -2 эн. +1 воды, +2 еды.",
    rarity: 2,
    canBeAutoSpawned: true,
    canDropFromEnemy: true,
  },
  meat_chunk: {
    effect: { food: 20, energy: 5, water: -2 },
    description: "Кусок мяса: +20 еды, +5 эн., -2 воды.",
    rarity: 2,
    canBeAutoSpawned: true,
    canDropFromEnemy: true,
  },
  blood_syringe: {
    effect: { health: 10 },
    description: "Шприц с кровью: +10 здоровья.",
    rarity: 2,
    canBeAutoSpawned: true,
    canDropFromEnemy: true,
  },
  milk: {
    effect: { water: 15, food: 5 },
    description: "Молоко: +15 воды, +5 еды.",
    rarity: 2,
    canBeAutoSpawned: true,
    canDropFromEnemy: true,
  },
  condensed_milk: {
    effect: { water: 5, food: 11, energy: 2 },
    description: "Сгущёнка: +11 еды, +5 воды, +2 эн.",
    rarity: 2,
    canBeAutoSpawned: true,
    canDropFromEnemy: true,
  },
  dried_fish: {
    effect: { food: 10, water: -3 },
    description: "Сушёная рыба: +10 еды, -3 воды.",
    rarity: 2,
    canBeAutoSpawned: true,
    canDropFromEnemy: true,
  },

  // === ВАЛЮТА ===
  balyary: {
    description: "Баляр: игровая валюта.",
    stackable: true,
    balyary: true,
    rarity: 1,
    canBeAutoSpawned: true,
    canDropFromEnemy: true,
  },

  // === СПЕЦПРЕДМЕТЫ ===
  atom: {
    effect: { armor: 5 },
    description: "Атом — даёт +5 брони при использовании.",
    stackable: true,
    rarity: 1,
    canBeAutoSpawned: true,
    canDropFromEnemy: true,
  },
  medical_certificate: {
    description: "Мед. справка МД-07: подтверждает, что ты не зомби.",
    rarity: 5,
    canBeAutoSpawned: false,
    canDropFromEnemy: false,
  },
  medical_certificate_stamped: {
    description: "Мед. справка с печатью заставы. Допуск в Неоновый Город.",
    rarity: 5,
    canBeAutoSpawned: false,
    canDropFromEnemy: false,
  },

  // === КИБЕР-ЭКИПИРОВКА (ЭНДГЕЙМ) ===
  cyber_helmet: {
    type: "headgear",
    effect: { armor: 10, energy: 5 },
    description: "Кибершлем: +10 брони, +5 энергии",
    rarity: 4,
    level: 5,
    canBeAutoSpawned: false,
    canDropFromEnemy: false,
  },
  nano_armor: {
    type: "armor",
    effect: { armor: 20, health: 10 },
    description: "Нано-броня: +20 брони, +10 здоровья",
    rarity: 4,
    level: 5,
    canBeAutoSpawned: false,
    canDropFromEnemy: false,
  },
  tactical_belt: {
    type: "belt",
    effect: { armor: 5, food: 5 },
    description: "Тактический пояс: +5 брони, +5 еды",
    rarity: 4,
    level: 5,
    canBeAutoSpawned: false,
    canDropFromEnemy: false,
  },
  cyber_pants: {
    type: "pants",
    effect: { armor: 10, water: 5 },
    description: "Киберштаны: +10 брони, +5 воды",
    rarity: 4,
    level: 5,
    canBeAutoSpawned: false,
    canDropFromEnemy: false,
  },
  speed_boots: {
    type: "boots",
    effect: { armor: 5, energy: 10 },
    description: "Скоростные ботинки: +5 брони, +10 энергии",
    rarity: 4,
    level: 5,
    canBeAutoSpawned: false,
    canDropFromEnemy: false,
  },
  tech_gloves: {
    type: "gloves",
    effect: { armor: 5, energy: 5 },
    description: "Технические перчатки: +5 брони, +5 энергии",
    rarity: 4,
    level: 5,
    canBeAutoSpawned: false,
    canDropFromEnemy: false,
  },
  plasma_rifle: {
    type: "weapon",
    effect: { damage: 50, range: 200 },
    description: "Плазменная винтовка: 50 урона, дальность 200px",
    rarity: 4,
    hands: "twohanded",
    level: 0,
    canBeAutoSpawned: false,
    canDropFromEnemy: false,
  },
  knuckles: {
    type: "weapon",
    effect: { damage: { min: 3, max: 7 } },
    description: "Кастет: 3–7 урона в ближнем бою",
    rarity: 4,
    hands: "onehanded",
    level: 2,
    canBeAutoSpawned: false,
    canDropFromEnemy: true,
  },
  knife: {
    type: "weapon",
    effect: { damage: { min: 4, max: 6 } },
    description: "Нож: 4–6 урона в ближнем бою",
    rarity: 4,
    hands: "onehanded",
    level: 3,
    canBeAutoSpawned: false,
    canDropFromEnemy: true,
  },
  nano_absorbing_knife: {
    type: "weapon",
    effect: { damage: { min: 6, max: 9 } },
    description: "Нож: 6–9 урона в ближнем бою",
    rarity: 4,
    hands: "onehanded",
    level: 3,
    canBeAutoSpawned: false,
    canDropFromEnemy: false,
  },
  bat: {
    type: "weapon",
    effect: { damage: { min: 5, max: 10 } },
    description: "Бита: 5–10 урона в ближнем бою",
    rarity: 4,
    hands: "onehanded",
    level: 4,
    canBeAutoSpawned: false,
    canDropFromEnemy: true,
  },

  // === НОВАЯ ПОРВАННАЯ ЭКИПИРОВКА (СТАРТОВАЯ ===
  torn_baseball_cap_of_health: {
    type: "headgear",
    effect: { armor: 5, health: 5 },
    description:
      "Порванная кепка здоровья: +5 к максимальному здоровью и броне",
    rarity: 4,
    collection: "Torn Health",
    level: 0,
    canBeAutoSpawned: false,
    canDropFromEnemy: true,
  },
  torn_health_t_shirt: {
    type: "armor",
    effect: { armor: 10, health: 10 },
    description:
      "Порванная футболка здоровья: +10 к максимальному здоровью, +10 к броне",
    rarity: 4,
    collection: "Torn Health",
    level: 0,
    canBeAutoSpawned: false,
    canDropFromEnemy: true,
  },
  torn_health_gloves: {
    type: "gloves",
    effect: { armor: 5, health: 3 },
    description:
      "Порванные перчатки здоровья: +3 к максимальному здоровью, +5 к броне",
    rarity: 4,
    collection: "Torn Health",
    level: 0,
    canBeAutoSpawned: false,
    canDropFromEnemy: true,
  },
  torn_belt_of_health: {
    type: "belt",
    effect: { armor: 3, health: 7 },
    description:
      "Порванный пояс здоровья: +7 к максимальному здоровью, +3 к броне",
    rarity: 4,
    collection: "Torn Health",
    level: 0,
    canBeAutoSpawned: false,
    canDropFromEnemy: true,
  },
  torn_pants_of_health: {
    type: "pants",
    effect: { armor: 7, health: 6 },
    description:
      "Порванные штаны здоровья: +6 к максимальному здоровью, +7 к броне",
    rarity: 4,
    collection: "Torn Health",
    level: 0,
    canBeAutoSpawned: false,
    canDropFromEnemy: true,
  },
  torn_health_sneakers: {
    type: "boots",
    effect: { armor: 5, health: 4 },
    description:
      "Порванные кроссовки здоровья: +4 к максимальному здоровью, +5 к броне",
    rarity: 4,
    collection: "Torn Health",
    level: 0,
    canBeAutoSpawned: false,
    canDropFromEnemy: true,
  },

  torn_energy_cap: {
    type: "headgear",
    effect: { armor: 5, energy: 5 },
    description:
      "Порванная кепка энергии: +5 к максимальной энергии, +5 к броне",
    rarity: 4,
    collection: "Torn Energy",
    level: 0,
    canBeAutoSpawned: false,
    canDropFromEnemy: true,
  },
  torn_energy_t_shirt: {
    type: "armor",
    effect: { armor: 10, energy: 10 },
    description:
      "Порванная футболка энергии: +10 к максимальной энергии, +10 к броне",
    rarity: 4,
    collection: "Torn Energy",
    level: 0,
    canBeAutoSpawned: false,
    canDropFromEnemy: true,
  },
  torn_gloves_of_energy: {
    type: "gloves",
    effect: { armor: 5, energy: 3 },
    description:
      "Порванные перчатки энергии: +3 к максимальной энергии, +5 к броне",
    rarity: 4,
    collection: "Torn Energy",
    level: 0,
    canBeAutoSpawned: false,
    canDropFromEnemy: true,
  },
  torn_energy_belt: {
    type: "belt",
    effect: { armor: 3, energy: 7 },
    description:
      "Порванный пояс энергии: +7 к максимальной энергии, +3 к броне",
    rarity: 4,
    collection: "Torn Energy",
    level: 0,
    canBeAutoSpawned: false,
    canDropFromEnemy: true,
  },
  torn_pants_of_energy: {
    type: "pants",
    effect: { armor: 7, energy: 6 },
    description:
      "Порванные штаны энергии: +6 к максимальной энергии, +7 к броне",
    rarity: 4,
    collection: "Torn Energy",
    level: 0,
    canBeAutoSpawned: false,
    canDropFromEnemy: true,
  },
  torn_sneakers_of_energy: {
    type: "boots",
    effect: { armor: 5, energy: 4 },
    description:
      "Порванные кроссовки энергии: +4 к максимальной энергии, +5 к броне",
    rarity: 4,
    collection: "Torn Energy",
    level: 0,
    canBeAutoSpawned: false,
    canDropFromEnemy: true,
  },

  torn_cap_of_gluttony: {
    type: "headgear",
    effect: { armor: 5, food: 5 },
    description: "Порванная кепка обжорства: +5 к максимальной еде, +5 к броне",
    rarity: 4,
    collection: "Torn Gluttony",
    level: 0,
    canBeAutoSpawned: false,
    canDropFromEnemy: true,
  },
  torn_t_shirt_of_gluttony: {
    type: "armor",
    effect: { armor: 10, food: 10 },
    description:
      "Порванная футболка обжорства: +10 к максимальной еде, +10 к броне",
    rarity: 4,
    collection: "Torn Gluttony",
    level: 0,
    canBeAutoSpawned: false,
    canDropFromEnemy: true,
  },
  torn_gloves_of_gluttony: {
    type: "gloves",
    effect: { armor: 5, food: 3 },
    description:
      "Порванные перчатки обжорства: +3 к максимальной еде, +5 к броне",
    rarity: 4,
    collection: "Torn Gluttony",
    level: 0,
    canBeAutoSpawned: false,
    canDropFromEnemy: true,
  },
  torn_belt_of_gluttony: {
    type: "belt",
    effect: { armor: 3, food: 7 },
    description: "Порванный пояс обжорства: +7 к максимальной еде, +3 к броне",
    rarity: 4,
    collection: "Torn Gluttony",
    level: 0,
    canBeAutoSpawned: false,
    canDropFromEnemy: true,
  },
  torn_pants_of_gluttony: {
    type: "pants",
    effect: { armor: 7, food: 6 },
    description: "Порванные штаны обжорства: +6 к максимальной еде, +7 к броне",
    rarity: 4,
    collection: "Torn Gluttony",
    level: 0,
    canBeAutoSpawned: false,
    canDropFromEnemy: true,
  },
  torn_sneakers_of_gluttony: {
    type: "boots",
    effect: { armor: 5, food: 4 },
    description:
      "Порванные кроссовки обжорства: +4 к максимальной еде, +5 к броне",
    rarity: 4,
    collection: "Torn Gluttony",
    level: 0,
    canBeAutoSpawned: false,
    canDropFromEnemy: true,
  },

  torn_cap_of_thirst: {
    type: "headgear",
    effect: { armor: 5, water: 5 },
    description: "Порванная кепка жажды: +5 к максимальной воде, +5 к броне",
    rarity: 4,
    collection: "Torn Thirst",
    level: 0,
    canBeAutoSpawned: false,
    canDropFromEnemy: true,
  },
  torn_t_shirt_of_thirst: {
    type: "armor",
    effect: { armor: 10, water: 10 },
    description:
      "Порванная футболка жажды: +10 к максимальной воде, +10 к броне",
    rarity: 4,
    collection: "Torn Thirst",
    level: 0,
    canBeAutoSpawned: false,
    canDropFromEnemy: true,
  },
  torn_gloves_of_thirst: {
    type: "gloves",
    effect: { armor: 5, water: 3 },
    description: "Порванные перчатки жажды: +3 к максимальной воде, +5 к броне",
    rarity: 4,
    collection: "Torn Thirst",
    level: 0,
    canBeAutoSpawned: false,
    canDropFromEnemy: true,
  },
  torn_belt_of_thirst: {
    type: "belt",
    effect: { armor: 3, water: 7 },
    description: "Порванный пояс жажды: +7 к максимальной воде, +3 к броне",
    rarity: 4,
    collection: "Torn Thirst",
    level: 0,
    canBeAutoSpawned: false,
    canDropFromEnemy: true,
  },
  torn_pants_of_thirst: {
    type: "pants",
    effect: { armor: 7, water: 6 },
    description: "Порванные штаны жажды: +6 к максимальной воде, +7 к броне",
    rarity: 4,
    collection: "Torn Thirst",
    level: 0,
    canBeAutoSpawned: false,
    canDropFromEnemy: true,
  },
  torn_sneakers_of_thirst: {
    type: "boots",
    effect: { armor: 5, water: 4 },
    description:
      "Порванные кроссовки жажды: +4 к максимальной воде, +5 к броне",
    rarity: 4,
    collection: "Torn Thirst",
    level: 0,
    canBeAutoSpawned: false,
    canDropFromEnemy: true,
  },

  chameleon_belt: {
    type: "belt",
    effect: { armor: 12, health: 14, energy: 7, food: 7, water: 7 },
    description:
      "Хамелеон пояс: +12 брони, +14 здоровья, +7 энергии, +7 еды, +7 воды",
    rarity: 4,
    collection: "Light Chameleon",
    level: 5,
    canBeAutoSpawned: false,
    canDropFromEnemy: true,
  },
  chameleon_cap: {
    type: "headgear",
    effect: { armor: 15, health: 10, energy: 5, food: 5, water: 5 },
    description:
      "Хамелеон кепка: +15 брони, +10 здоровья, +5 энергии, +5 еды, +5 воды",
    rarity: 4,
    collection: "Light Chameleon",
    level: 5,
    canBeAutoSpawned: false,
    canDropFromEnemy: true,
  },
  chameleon_gloves: {
    type: "gloves",
    effect: { armor: 20, health: 6, energy: 3, food: 3, water: 3 },
    description:
      "Хамелеон перчатки: +20 брони, +6 здоровья, +3 энергии, +3 еды, +3 воды",
    rarity: 4,
    collection: "Light Chameleon",
    level: 5,
    canBeAutoSpawned: false,
    canDropFromEnemy: true,
  },
  chameleon_pants: {
    type: "pants",
    effect: { armor: 21, health: 12, energy: 6, food: 6, water: 6 },
    description:
      "Хамелеон штаны: +21 брони, +12 здоровья, +6 энергии, +6 еды, +6 воды",
    rarity: 4,
    collection: "Light Chameleon",
    level: 5,
    canBeAutoSpawned: false,
    canDropFromEnemy: true,
  },
  chameleon_sneakers: {
    type: "boots",
    effect: { armor: 15, health: 8, energy: 4, food: 4, water: 4 },
    description:
      "Хамелеон кроссовки: +15 брони, +8 здоровья, +4 энергии, +4 еды, +4 воды",
    rarity: 4,
    collection: "Light Chameleon",
    level: 5,
    canBeAutoSpawned: false,
    canDropFromEnemy: true,
  },
  chameleon_t_shirt: {
    type: "armor",
    effect: { armor: 30, health: 20, energy: 10, food: 10, water: 10 },
    description:
      "Хамелеон футболка: +30 брони, +20 здоровья, +10 энергии, +10 еды, +10 воды",
    rarity: 4,
    collection: "Light Chameleon",
    level: 5,
    canBeAutoSpawned: false,
    canDropFromEnemy: true,
  },

  white_void_cap: {
    type: "headgear",
    effect: {},
    description: "Белая кепка Пустоты — чистый лист для будущих улучшений",
    rarity: 4,
    collection: "White Void",
    level: 0,
    canBeAutoSpawned: false,
    canDropFromEnemy: true,
  },
  white_void_t_shirt: {
    type: "armor",
    effect: {},
    description: "Белая футболка Пустоты — чистый лист для будущих улучшений",
    rarity: 4,
    collection: "White Void",
    level: 0,
    canBeAutoSpawned: false,
    canDropFromEnemy: true,
  },
  white_void_gloves: {
    type: "gloves",
    effect: {},
    description: "Белые перчатки Пустоты — чистый лист для будущих улучшений",
    rarity: 4,
    collection: "White Void",
    level: 0,
    canBeAutoSpawned: false,
    canDropFromEnemy: true,
  },
  white_void_belt: {
    type: "belt",
    effect: {},
    description: "Белый пояс Пустоты — чистый лист для будущих улучшений",
    rarity: 4,
    collection: "White Void",
    level: 0,
    canBeAutoSpawned: false,
    canDropFromEnemy: true,
  },
  white_void_pants: {
    type: "pants",
    effect: {},
    description: "Белые штаны Пустоты — чистый лист для будущих улучшений",
    rarity: 4,
    collection: "White Void",
    level: 0,
    canBeAutoSpawned: false,
    canDropFromEnemy: true,
  },
  white_void_sneakers: {
    type: "boots",
    effect: {},
    description: "Белые кроссовки Пустоты — чистый лист для будущих улучшений",
    rarity: 4,
    collection: "White Void",
    level: 0,
    canBeAutoSpawned: false,
    canDropFromEnemy: true,
  },

  recipe_torn_equipment: {
    effect: {},
    description:
      "Рецепт порванной экипировки — материал для улучшений у Торестоса",
    rarity: 6,
    stackable: true,
    recipe: "recipe_torn_equipment",
    canBeAutoSpawned: false,
    canDropFromEnemy: true,
  },

  recipe_chameleon_equipment: {
    effect: {},
    description:
      "Рецепт хамелеон-экипировки — материал для улучшений у Торестоса",
    rarity: 6,
    stackable: true,
    recipe: "recipe_chameleon_equipment",
    canBeAutoSpawned: false,
    canDropFromEnemy: true,
  },

  blue_crystal: {
    description: "Синий кристал — материал для улучшений у Торестоса",
    rarity: 1,
    stackable: true,
    canBeAutoSpawned: true,
    canDropFromEnemy: false,
  },
  green_crystal: {
    description: "Зеленый кристал — материал для улучшений у Торестоса",
    rarity: 1,
    stackable: true,
    canBeAutoSpawned: true,
    canDropFromEnemy: false,
  },
  red_crystal: {
    description: "Красный кристал — материал для улучшений у Торестоса",
    rarity: 1,
    stackable: true,
    canBeAutoSpawned: true,
    canDropFromEnemy: false,
  },
  white_crystal: {
    description: "Белый кристал — материал для улучшений у Торестоса",
    rarity: 1,
    stackable: true,
    canBeAutoSpawned: true,
    canDropFromEnemy: false,
  },
  yellow_crystal: {
    description: "Желтый кристал — материал для улучшений у Торестоса",
    rarity: 1,
    stackable: true,
    canBeAutoSpawned: true,
    canDropFromEnemy: false,
  },
  chameleon_crystal: {
    description: "Хамелион кристал — материал для улучшений у Торестоса",
    rarity: 1,
    stackable: true,
    canBeAutoSpawned: true,
    canDropFromEnemy: false,
  },
  nanoalloy: {
    description: "Наносплав.",
    rarity: 1,
    stackable: true,
    canBeAutoSpawned: true,
    canDropFromEnemy: false,
  },
  nanofilament: {
    description: "Нановолокно.",
    rarity: 1,
    stackable: true,
    canBeAutoSpawned: true,
    canDropFromEnemy: false,
  },
};

module.exports = { ITEM_CONFIG };
